### ISSUE TITLE
pypi release

### ISSUE THREAD

**Issue by uSpike** [kontron/robotframework-ipmilibrary#1]
Hi!

This library is very cool, and I have some uses for it.  Is there a release planned for PyPI?

Thanks!

**Comment by hthiery** [comment]
Hi,

just did a release on pypi.

Heiko

**Comment by uSpike** [comment]
Thanks very much!  Hopefully we'll be able to use it and contribute :+1:

**Comment by hthiery** [comment]
what kind of device do you plan to test and what interface do you use? RMCP?

2016-03-30 16:08 GMT+02:00 Jordan Speicher notifications@github.com:

**Comment by uSpike** [comment]
We are testing two use cases for now:
- On-board IPMC via serial-terminal interface from a SBC
- The same test, but via lan interface to BMC (VPX ChMC in this case), which connects to IPMCs via backplane IPMB.
